// uvm_dpi_verilator.cpp
// Compiles UVM DPI C sources with C linkage for Verilator on macOS.
// Provides stubs for VPI runtime and HDL backdoor (not supported by Verilator).

#include <stdlib.h>
#include <limits.h>
#include <string.h>
#include "svdpi.h"
#include "vpi_user.h"

// -----------------------------------------------------------------------
// VPI stub: called by uvm_svcmd_dpi.c to get tool name/version/plusargs.
// -----------------------------------------------------------------------
extern "C" PLI_INT32 vpi_get_vlog_info(p_vpi_vlog_info vlog_info_p) {
    if (vlog_info_p) {
        vlog_info_p->argc    = 0;
        vlog_info_p->argv    = nullptr;
        vlog_info_p->product = (PLI_BYTE8*)"Verilator";
        vlog_info_p->version = (PLI_BYTE8*)"5.x";
    }
    return 1;
}

// -----------------------------------------------------------------------
// Include UVM DPI C sources inside extern "C" so their symbols get C
// linkage, matching the extern "C" wrappers generated by Verilator.
// -----------------------------------------------------------------------
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"
#pragma clang diagnostic ignored "-Wformat-security"
#pragma clang diagnostic ignored "-Wdeprecated"

// uvm_dpi_srcs.h is generated by the Makefile — it contains the three
// #include lines for the UVM DPI C sources with the correct absolute paths.
extern "C" {
#include "uvm_dpi_srcs.h"
}

#pragma clang diagnostic pop

// -----------------------------------------------------------------------
// HDL backdoor stubs — signatures match uvm_dpi.h exactly (char*, p_vpi_vecval).
// Never called in a pure UVM test.
// -----------------------------------------------------------------------
extern "C" {
    int uvm_hdl_check_path(char* path)                           { (void)path; return 0; }
    int uvm_hdl_read(char* path, p_vpi_vecval value)             { (void)path; (void)value; return 0; }
    int uvm_hdl_deposit(char* path, p_vpi_vecval value)          { (void)path; (void)value; return 0; }
    int uvm_hdl_force(char* path, p_vpi_vecval value)            { (void)path; (void)value; return 0; }
    int uvm_hdl_release(char* path)                              { (void)path; return 0; }
    int uvm_hdl_release_and_read(char* path, p_vpi_vecval value) { (void)path; (void)value; return 0; }
}
